version: '3'
services:
  database:
    build: 
      context: ./database/
      dockerfile: Dockerfile
  backend:
    build: 
      context: ./backend/
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "4000:8000"
    depends_on:
      - database