version: '3'
services:
  database:
    # image:
    #   kanishmathee/tabletennisproject:master_database
    build: 
      context: ./database/
      dockerfile: Dockerfile
  backend:
    # image:
    #   kanishmathee/tabletennisproject:master_backend
    build: 
      context: ./backend/
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "4000:9000"
    depends_on:
      - database