# Generated by Django 2.1.5 on 2019-01-24 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamMatches', '0002_auto_20190122_1036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['id']},
        ),
    ]
