# Generated by Django 2.1.5 on 2019-01-25 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamMatches', '0003_auto_20190124_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_team', to='TeamMatches.Team'),
        ),
    ]
