# Generated by Django 2.1.5 on 2019-02-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamMatches', '0004_match_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_type',
            field=models.IntegerField(choices=[(1, 'GROUP_STAGE'), (2, 'FINALS')], default=1),
        ),
    ]
