# Generated by Django 2.1.5 on 2019-01-22 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('total_matches', models.IntegerField(blank=True, default=0)),
                ('number_of_matches_played', models.IntegerField(blank=True, default=0)),
                ('won', models.IntegerField(blank=True, default=0)),
                ('lost', models.IntegerField(blank=True, default=0)),
                ('point_difference', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('group_image', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('credit_value', models.IntegerField(default=0)),
                ('group_name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='Users.Group')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
