# Generated by Django 2.1.5 on 2019-01-17 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group_image',
        ),
    ]
