# Generated by Django 2.1.5 on 2019-01-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_remove_group_group_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
