# Generated by Django 2.1.5 on 2019-01-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamMatches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_status',
            field=models.IntegerField(choices=[(1, 'COMPLETED'), (2, 'LIVE'), (3, 'SCHEDULED')], default=3),
        ),
    ]
