# Generated by Django 2.1.5 on 2019-01-17 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamMatches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='name',
        ),
    ]
