# Generated by Django 2.1.5 on 2019-01-22 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamMatches', '0004_match_match_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='set',
            unique_together={('match', 'set_name')},
        ),
    ]
