# Generated by Django 2.1.5 on 2019-01-22 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamMatches', '0005_auto_20190122_0515'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='set',
            unique_together=set(),
        ),
    ]
